=== gitter-badger/insulae-public/island-exports/insulae_insel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema erstellt von Jan H. Krueger-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="y" type="xs:integer"/>
	<xs:element name="x" type="xs:integer"/>
	<xs:element name="w" type="xs:integer"/>
	<xs:element name="entdeckt" type="xs:string"/>
	<xs:element name="bebaubar" type="xs:string"/>
	<xs:element name="Ursprung" type="xs:string"/>
	<xs:element name="Strasse" type="xs:string"/>
	<xs:element name="Wirksamkeitsdatum" type="xs:string"/>
	<xs:element name="Position">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="x"/>
				<xs:element ref="y"/>
				<xs:element ref="w"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Landwert" type="xs:byte"/>
	<xs:element name="Landart" type="xs:integer"/>
	<xs:element name="Jahreszeit" type="xs:string"/>
	<xs:element name="Inselrealisierung">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Feld" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Inselname" type="xs:string"/>
	<xs:element name="Inselheader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Inselname"/>
				<xs:element ref="ID"/>
				<xs:element ref="Ursprung"/>
				<xs:element ref="Ersteller"/>
				<xs:element ref="entdeckt"/>
				<xs:element ref="Jahreszeit"/>
				<xs:element ref="Wirksamkeitsdatum"/>
				<xs:element ref="Beschreibung"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Insel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Inselheader"/>
				<xs:element ref="Inselrealisierung"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ID" type="xs:integer"/>
	<xs:element name="Gelaende" type="xs:short"/>
	<xs:element name="Feldoptionen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="bebaubar"/>
				<xs:element ref="Strasse"/>
				<xs:element ref="Landwert"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Feldart">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Landart"/>
				<xs:element ref="Gelaende"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Feld">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Position"/>
				<xs:element ref="Feldart"/>
				<xs:element ref="Feldoptionen"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Ersteller" type="xs:string"/>
	<xs:element name="Beschreibung" type="xs:string"/>
</xs:schema>

=== gitter-badger/insulae-public/island-exports/Edelstein-Insel.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Insel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="insulae_insel.xsd">
    <Inselheader>
        <Inselname>Edelstein-Insel</Inselname>
        <ID>14</ID>
        <Ursprung>SW-Beta</Ursprung>
        <Ersteller>unbekannt</Ersteller>
        <entdeckt>n</entdeckt>
        <Jahreszeit>1</Jahreszeit>
        <Wirksamkeitsdatum>2016-05-30</Wirksamkeitsdatum>
    </Inselheader>
    <Inselrealisierung>
        <Feld>
            <Position>
                <x>-385</x>
                <y>2</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>462</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-385</x>
                <y>2</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>462</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-385</x>
                <y>3</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>463</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-385</x>
                <y>3</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>463</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-385</x>
                <y>4</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>465</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-385</x>
                <y>4</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>465</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-385</x>
                <y>5</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>490</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-385</x>
                <y>5</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>490</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>0</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>411</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>0</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>411</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>1</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>403</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>1</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>403</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>2</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>202</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>2</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>202</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>3</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>205</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>3</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>205</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>4</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>208</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>4</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>208</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>5</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>483</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-386</x>
                <y>5</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>483</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
                <Strasse>j</Strasse>
                <Landwert>0</Landwert>
            </Feldoptionen>
        </Feld>
        <Feld>
            <Position>
                <x>-385</x>
                <y>0</y>
                <w>0</w>
            </Position>
            <Feldart>
                <Landart>1000000000</Landart>
                <Gelaende>430</Gelaende>
            </Feldart>
            <Feldoptionen>
                <bebaubar>j</bebaubar>
