=== gitter-badger/insulae-public/goods-export/insulae_waren.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema erstellt von Jan H. Krueger-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Herkunft" type="xs:string"/>
	<xs:element name="Wirksamkeitsdatum" type="xs:string"/>
	<xs:element name="Warenheader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Herkunft"/>
				<xs:element ref="Wirksamkeitsdatum"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ID" type="xs:integer"/>
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="Beschreibung" type="xs:string"/>
	<xs:element name="aktiv" type="xs:string"/>
	<xs:element name="Warenkorb">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ware" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Waren">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Warenheader"/>
				<xs:element ref="Warenkorb"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Ware">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ID"/>
				<xs:element ref="Name"/>
				<xs:element ref="Beschreibung"/>
				<xs:element ref="aktiv"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gitter-badger/insulae-public/goods-export/Insulae-Waren.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Waren xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="insulae_waren.xsd">
    <Warenheader>
        <Herkunft>Insulae</Herkunft>
        <Wirksamkeitsdatum>2016-06-03</Wirksamkeitsdatum>
    </Warenheader>
    <Warenkorb>
        <ID>1</ID>
        <Name>Holz</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>2</ID>
        <Name>Stein</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>3</ID>
        <Name>Gold</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>4</ID>
        <Name>Eisen</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>5</ID>
        <Name>Schafe</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>6</ID>
        <Name>Kühe</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>7</ID>
        <Name>Pferde</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>8</ID>
        <Name>Fleisch</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>9</ID>
        <Name>Getreide</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>10</ID>
        <Name>Brot</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>11</ID>
        <Name>Bier</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>12</ID>
        <Name>Bronze</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>13</ID>
        <Name>Werkzeuge</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>14</ID>
        <Name>Wein</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>15</ID>
        <Name>Fisch</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>16</ID>
        <Name>Lebertran</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>17</ID>
        <Name>Harz</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>18</ID>
        <Name>Schmuck</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>19</ID>
        <Name>Pilze</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>20</ID>
        <Name>Handelswaren</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>21</ID>
        <Name>Möbel</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>22</ID>
        <Name>Ziegel</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>23</ID>
        <Name>Kleidung</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>24</ID>
        <Name>Leder</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>25</ID>
        <Name>Wolpertinger</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>26</ID>
        <Name>Sklaven</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>27</ID>
        <Name>Waffen</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>28</ID>
        <Name>Rüstungen</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>29</ID>
        <Name>Schneemann</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>30</ID>
        <Name>Glas</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>31</ID>
        <Name>Bücher</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>32</ID>
        <Name>Edelsteine</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>33</ID>
        <Name>Kräuter</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>34</ID>
        <Name>Thaum</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>35</ID>
        <Name>Endurium</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>36</ID>
        <Name>Petroleum</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>37</ID>
        <Name>Kaffee</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>38</ID>
        <Name>Tabak</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>39</ID>
        <Name>Kakao</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>40</ID>
        <Name>Mahagonie</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>41</ID>
        <Name>Knochen</Name>
        <Beschreibung></Beschreibung>
        <aktiv>j</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>151</ID>
        <Name>Hanf</Name>
        <Beschreibung></Beschreibung>
        <aktiv>n</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>153</ID>
        <Name>Wasser</Name>
        <Beschreibung></Beschreibung>
        <aktiv>n</aktiv>
    </Warenkorb>
    <Warenkorb>
        <ID>154</ID>
        <Name>Kohle</Name>
        <Beschreibung></Beschreibung>
        <aktiv>n</aktiv>
    </Warenkorb>
</Waren>
